//
//  LocalPhotosRouter.swift
//  Uai Fotos
//
//  Created by Aloc SP08608 on 13/12/2017.
//  Copyright (c) 2017 Uai Fotos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LocalPhotosRoutingLogic {
    func navigateToPhotoDetail(values: (photo: PhotoDTO, friend: UserDTO))
}

protocol LocalPhotosDataPassing {
}

class LocalPhotosRouter: NSObject, LocalPhotosRoutingLogic, LocalPhotosDataPassing {
    
    weak var viewController: LocalPhotosViewController?
    var dataStore: LocalPhotosDataStore?
    
    var values: (photo: PhotoDTO, friend: UserDTO)?
    
    func navigateToPhotoDetail(values: (photo: PhotoDTO, friend: UserDTO)) {
        self.values = values
        viewController?.performSegue(withIdentifier: "PhotoDetail", sender: nil)
    }
    
    @objc func routeToPhotoDetailWithSegue(_ segue: UIStoryboardSegue?) {
        if let dest = segue?.destination as? ActivityDetailTableViewController, let values = values {
            dest.activityDetail = values
        }
    }
}
