//
//  LocalPhotosWorker.swift
//  Uai Fotos
//
//  Created by Aloc SP08608 on 13/12/2017.
//  Copyright (c) 2017 Uai Fotos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

class LocalPhotosWorker {

    func getPhotosByLocation(latitude : Double, longitude : Double) -> [(photo: PhotoDTO, friend: UserDTO)] {
        let qtPhotos = Int(arc4random_uniform(90))
//        return UaiFotosDataStore().generatePhotos(number: qtPhotos)
        let users = UaiFotosDataStore().generateUsers(number: qtPhotos)
        let photos = UaiFotosDataStore().generatePhotos(number: qtPhotos)
        var result = [(photo: PhotoDTO, friend: UserDTO)]()
        
        for i in 0 ..< qtPhotos {
            result.append((photo: photos[i], friend: users[i]))
        }
        
        return result

    }
}
